### ISSUE TITLE
Getting erros since pre-patch, unable to open conversations with NPC's now

### ISSUE THREAD

**Issue by Wheatleyzor** [Ellypse/Storyline#57] opened 2020-10-20 22:05 UTC
Seeing the following errors:

**Error 1**:
69x Storyline\lib\Ellyb\Tools\Colors-Colors.lua:44: attempt to compare number with nil
[string "@Storyline\lib\Ellyb\Tools\Colors-Colors.lua"]:44: in function `initialize'
[string "@Storyline\lib\Ellyb\Libraries\middleclass.lua"]:154: in function `new'
[string "@Storyline\lib\Ellyb\Tools\ColorsManager.lua"]:156: in main chunk

Locals:
self = <table> {
 class = <table> {
 }
}
red = nil
green = nil
blue = nil
alpha = nil
(*temporary) = "nil"
(*temporary) = nil
(*temporary) = "nil"
(*temporary) = <table> {
 canBeMutated = true
}
(*temporary) = <table> {
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
}
(*temporary) = "attempt to compare number with nil"
_privateInit = <function> defined @Storyline\lib\Ellyb\Tools\Colors.lua:19
Ellyb = <table> {

**Error 2**:
70x ...line\lib\CustomTutorials-2.1\CustomTutorials-2.1-8.lua:149: attempt to call method 'SetBackdrop' (a nil value)
[string "@Storyline\lib\CustomTutorials-2.1\CustomTutorials-2.1-8.lua"]:149: in function <...line\lib\CustomTutorials-2.1\CustomTutorials-2.1.lua:124>
[string "@Storyline\lib\CustomTutorials-2.1\CustomTutorials-2.1-8.lua"]:181: in function `RegisterTutorials'
[string "@Storyline\Tutorials.lua"]:28: in function `register'
[string "@Storyline\events.lua"]:842: in function `initEventsStructure'
[string "@Storyline\logic.lua"]:637: in function <Storyline\logic.lua:467>
[string "=[C]"]: ?
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@ElvUI_SLE\modules\professions\professions.lua"]:38: in function <ElvUI_SLE\modules\professions\professions.lua:35>
[string "=[C]"]: ?
[string "@ElvUI_SLE\core\toolkit.lua"]:307: in function `InitializeModules'
[string "@ElvUI_SLE\core\core.lua"]:85: in function `?'
[string "@ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0-36.lua"]:303: in function <...\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:299>
[string "=[C]"]: in function `Initialize'
[string "@ElvUI\init.lua"]:153: in function <ElvUI\init.lua:152>
[string "=[C]"]: ?
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>

**Error 3:**

4x Storyline\events.lua:786: attempt to call field 'text' (a nil value)
[string "@Storyline\events.lua"]:786: in function <Storyline\events.lua:784>

Locals:
(*temporary) = <function> defined @Storyline\logic.lua:196
(*temporary) = "npc"
(*temporary) = nil
(*temporary) = "attempt to call field 'text' (a nil value)"
storylineFrameShouldOpen = true
startDialog = <function> defined @Storyline\logic.lua:196
info = <table> {
 finishMethod = <function> defined @Storyline\events.lua:716
 finishText = <function> defined @Storyline\events.lua:727
}
event = "GOSSIP_SHOW"

Sorry for the wall of text!

**Comment by Ellypse** [comment] 2020-10-21 06:35
Duplicate of #56

**Closed by Ellypse** 2020-10-21 06:35 UTC
